
package com.bullhorn.apiservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.bullhorn.apiservice.query.DtoQuery;
import com.bullhorn.apiservice.result.ApiAddNoteReferenceResult;
import com.bullhorn.apiservice.result.ApiAssociateResult;
import com.bullhorn.apiservice.result.ApiEventsGetEventsResult;
import com.bullhorn.apiservice.result.ApiEventsGetLastRequestIdResult;
import com.bullhorn.apiservice.result.ApiEventsSubscribeResult;
import com.bullhorn.apiservice.result.ApiEventsUnsubscribeResult;
import com.bullhorn.apiservice.result.ApiFindMultipleResult;
import com.bullhorn.apiservice.result.ApiFindResult;
import com.bullhorn.apiservice.result.ApiGetAssociationIdsResult;
import com.bullhorn.apiservice.result.ApiGetDepartmentUserIdsResult;
import com.bullhorn.apiservice.result.ApiGetEntityMetadataResult;
import com.bullhorn.apiservice.result.ApiGetEntityNotesResult;
import com.bullhorn.apiservice.result.ApiGetNoteReferencesResult;
import com.bullhorn.apiservice.result.ApiGetUserDepartmentIdsResult;
import com.bullhorn.apiservice.result.ApiGetUserPrimaryDepartmentIdResult;
import com.bullhorn.apiservice.result.ApiGetUserTypesResult;
import com.bullhorn.apiservice.result.ApiQueryResult;
import com.bullhorn.apiservice.result.ApiRemoveNoteReferenceResult;
import com.bullhorn.apiservice.result.ApiResult;
import com.bullhorn.apiservice.result.ApiSaveResult;
import com.bullhorn.apiservice.result.ApiUnassociateResult;
import com.bullhorn.apiservice.session.ApiSession;
import com.bullhorn.dataevent.subscription.SubscriptionCriteria;
import com.bullhorn.entity.AbstractDto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-hudson-208-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ApiService", targetNamespace = "http://apiservice.bullhorn.com/")
@XmlSeeAlso({
    com.bullhorn.entity.appointment.ObjectFactory.class,
    com.bullhorn.entity.template.client.ObjectFactory.class,
    com.bullhorn.entity.client.ObjectFactory.class,
    com.bullhorn.apiservice.result.ObjectFactory.class,
    com.bullhorn.entity.template.ObjectFactory.class,
    com.bullhorn.entity.distlist.ObjectFactory.class,
    com.bullhorn.entity.housing.ObjectFactory.class,
    com.bullhorn.entity.ObjectFactory.class,
    com.bullhorn.apiservice.ObjectFactory.class,
    com.bullhorn.apiservice.query.ObjectFactory.class,
    com.bullhorn.entity.note.ObjectFactory.class,
    com.bullhorn.entity.test.ObjectFactory.class,
    com.bullhorn.entity.timecard.ObjectFactory.class,
    com.bullhorn.entity.lists.ObjectFactory.class,
    com.bullhorn.entity.emb.ObjectFactory.class,
    com.bullhorn.apiservice.session.ObjectFactory.class,
    com.bullhorn.apiservice.meta.ObjectFactory.class,
    com.bullhorn.dataevent.subscription.ObjectFactory.class,
    com.bullhorn.dataevent.event.ObjectFactory.class,
    com.bullhorn.entity.template.user.ObjectFactory.class,
    com.bullhorn.entity.job.ObjectFactory.class,
    com.bullhorn.entity.ratecard.ObjectFactory.class,
    com.bullhorn.entity.template.job.ObjectFactory.class,
    com.bullhorn.entity.task.ObjectFactory.class,
    com.bullhorn.dataevent.result.ObjectFactory.class,
    com.bullhorn.entity.cert.ObjectFactory.class,
    com.bullhorn.entity.invoice.ObjectFactory.class,
    com.bullhorn.entity.tearsheet.ObjectFactory.class,
    com.bullhorn.entity.privatelabel.ObjectFactory.class,
    com.bullhorn.entity.userwork.ObjectFactory.class,
    com.bullhorn.entity.corp.ObjectFactory.class,
    com.bullhorn.entity.user.ObjectFactory.class,
    com.bullhorn.entity.candidate.ObjectFactory.class,
    com.bullhorn.entity.survey.ObjectFactory.class
})
public interface ApiService {


    /**
     * 
     * @param id
     * @param session
     * @param entityName
     * @return
     *     returns com.bullhorn.apiservice.result.ApiFindResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "find", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.Find")
    @ResponseWrapper(localName = "findResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.FindResponse")
    public ApiFindResult find(
        @WebParam(name = "session", targetNamespace = "")
        ApiSession session,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "id", targetNamespace = "")
        Object id);

    /**
     * 
     * @param dto
     * @param session
     * @return
     *     returns com.bullhorn.apiservice.result.ApiSaveResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "save", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.SaveResponse")
    public ApiSaveResult save(
        @WebParam(name = "session", targetNamespace = "")
        ApiSession session,
        @WebParam(name = "dto", targetNamespace = "")
        AbstractDto dto);

    /**
     * 
     * @param dto
     * @param session
     * @return
     *     returns com.bullhorn.apiservice.result.ApiResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delete", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.DeleteResponse")
    public ApiResult delete(
        @WebParam(name = "session", targetNamespace = "")
        ApiSession session,
        @WebParam(name = "dto", targetNamespace = "")
        AbstractDto dto);

    /**
     * 
     * @param session
     * @param query
     * @return
     *     returns com.bullhorn.apiservice.result.ApiQueryResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "query", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.Query")
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.QueryResponse")
    public ApiQueryResult query(
        @WebParam(name = "session", targetNamespace = "")
        ApiSession session,
        @WebParam(name = "query", targetNamespace = "")
        DtoQuery query);

    /**
     * 
     * @param id
     * @param associateId
     * @param associationName
     * @param session
     * @param entityName
     * @return
     *     returns com.bullhorn.apiservice.result.ApiAssociateResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "associate", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.Associate")
    @ResponseWrapper(localName = "associateResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.AssociateResponse")
    public ApiAssociateResult associate(
        @WebParam(name = "session", targetNamespace = "")
        ApiSession session,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "id", targetNamespace = "")
        Object id,
        @WebParam(name = "associationName", targetNamespace = "")
        String associationName,
        @WebParam(name = "associateId", targetNamespace = "")
        Object associateId);

    /**
     * 
     * @param username
     * @param password
     * @param apiKey
     * @return
     *     returns com.bullhorn.apiservice.session.ApiSession
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "startSession", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.StartSession")
    @ResponseWrapper(localName = "startSessionResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.StartSessionResponse")
    public ApiSession startSession(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "apiKey", targetNamespace = "")
        String apiKey);

    /**
     * 
     * @param session
     * @param ids
     * @param entityName
     * @return
     *     returns com.bullhorn.apiservice.result.ApiFindMultipleResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findMultiple", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.FindMultiple")
    @ResponseWrapper(localName = "findMultipleResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.FindMultipleResponse")
    public ApiFindMultipleResult findMultiple(
        @WebParam(name = "session", targetNamespace = "")
        ApiSession session,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "ids", targetNamespace = "")
        List<Object> ids);

    /**
     * 
     * @param id
     * @param session
     * @param entityName
     * @return
     *     returns com.bullhorn.apiservice.result.ApiResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteById", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.DeleteById")
    @ResponseWrapper(localName = "deleteByIdResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.DeleteByIdResponse")
    public ApiResult deleteById(
        @WebParam(name = "session", targetNamespace = "")
        ApiSession session,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "id", targetNamespace = "")
        Object id);

    /**
     * 
     * @param id
     * @param associationName
     * @param session
     * @param entityName
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetAssociationIdsResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAssociationIds", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetAssociationIds")
    @ResponseWrapper(localName = "getAssociationIdsResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetAssociationIdsResponse")
    public ApiGetAssociationIdsResult getAssociationIds(
        @WebParam(name = "session", targetNamespace = "")
        ApiSession session,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "id", targetNamespace = "")
        Object id,
        @WebParam(name = "associationName", targetNamespace = "")
        String associationName);

    /**
     * 
     * @param id
     * @param associationName
     * @param session
     * @param associateIds
     * @param entityName
     * @return
     *     returns com.bullhorn.apiservice.result.ApiAssociateResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "associateMultiple", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.AssociateMultiple")
    @ResponseWrapper(localName = "associateMultipleResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.AssociateMultipleResponse")
    public ApiAssociateResult associateMultiple(
        @WebParam(name = "session", targetNamespace = "")
        ApiSession session,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "id", targetNamespace = "")
        Object id,
        @WebParam(name = "associationName", targetNamespace = "")
        String associationName,
        @WebParam(name = "associateIds", targetNamespace = "")
        List<Object> associateIds);

    /**
     * 
     * @param id
     * @param associateId
     * @param associationName
     * @param session
     * @param entityName
     * @return
     *     returns com.bullhorn.apiservice.result.ApiUnassociateResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "unassociate", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.Unassociate")
    @ResponseWrapper(localName = "unassociateResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.UnassociateResponse")
    public ApiUnassociateResult unassociate(
        @WebParam(name = "session", targetNamespace = "")
        ApiSession session,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "id", targetNamespace = "")
        Object id,
        @WebParam(name = "associationName", targetNamespace = "")
        String associationName,
        @WebParam(name = "associateId", targetNamespace = "")
        Object associateId);

    /**
     * 
     * @param id
     * @param associationName
     * @param session
     * @param associateIds
     * @param entityName
     * @return
     *     returns com.bullhorn.apiservice.result.ApiUnassociateResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "unassociateMultiple", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.UnassociateMultiple")
    @ResponseWrapper(localName = "unassociateMultipleResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.UnassociateMultipleResponse")
    public ApiUnassociateResult unassociateMultiple(
        @WebParam(name = "session", targetNamespace = "")
        ApiSession session,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "id", targetNamespace = "")
        Object id,
        @WebParam(name = "associationName", targetNamespace = "")
        String associationName,
        @WebParam(name = "associateIds", targetNamespace = "")
        List<Object> associateIds);

    /**
     * 
     * @param session
     * @param departmentId
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetDepartmentUserIdsResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDepartmentUserIds", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetDepartmentUserIds")
    @ResponseWrapper(localName = "getDepartmentUserIdsResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetDepartmentUserIdsResponse")
    public ApiGetDepartmentUserIdsResult getDepartmentUserIds(
        @WebParam(name = "session", targetNamespace = "")
        ApiSession session,
        @WebParam(name = "departmentId", targetNamespace = "")
        Integer departmentId);

    /**
     * 
     * @param session
     * @param corporateUserId
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetUserDepartmentIdsResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserDepartmentIds", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetUserDepartmentIds")
    @ResponseWrapper(localName = "getUserDepartmentIdsResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetUserDepartmentIdsResponse")
    public ApiGetUserDepartmentIdsResult getUserDepartmentIds(
        @WebParam(name = "session", targetNamespace = "")
        ApiSession session,
        @WebParam(name = "corporateUserId", targetNamespace = "")
        Integer corporateUserId);

    /**
     * 
     * @param session
     * @param corporateUserId
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetUserPrimaryDepartmentIdResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserPrimaryDepartmentId", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetUserPrimaryDepartmentId")
    @ResponseWrapper(localName = "getUserPrimaryDepartmentIdResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetUserPrimaryDepartmentIdResponse")
    public ApiGetUserPrimaryDepartmentIdResult getUserPrimaryDepartmentId(
        @WebParam(name = "session", targetNamespace = "")
        ApiSession session,
        @WebParam(name = "corporateUserId", targetNamespace = "")
        Integer corporateUserId);

    /**
     * 
     * @param session
     * @param personEntityName
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetUserTypesResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserTypes", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetUserTypes")
    @ResponseWrapper(localName = "getUserTypesResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetUserTypesResponse")
    public ApiGetUserTypesResult getUserTypes(
        @WebParam(name = "session", targetNamespace = "")
        ApiSession session,
        @WebParam(name = "personEntityName", targetNamespace = "")
        String personEntityName);

    /**
     * 
     * @param criteria
     * @param session
     * @param subscriptionId
     * @return
     *     returns com.bullhorn.apiservice.result.ApiEventsSubscribeResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "eventsSubscribe", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.EventsSubscribe")
    @ResponseWrapper(localName = "eventsSubscribeResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.EventsSubscribeResponse")
    public ApiEventsSubscribeResult eventsSubscribe(
        @WebParam(name = "session", targetNamespace = "")
        ApiSession session,
        @WebParam(name = "subscriptionId", targetNamespace = "")
        String subscriptionId,
        @WebParam(name = "criteria", targetNamespace = "")
        SubscriptionCriteria criteria);

    /**
     * 
     * @param session
     * @param subscriptionId
     * @return
     *     returns com.bullhorn.apiservice.result.ApiEventsUnsubscribeResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "eventsUnsubscribe", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.EventsUnsubscribe")
    @ResponseWrapper(localName = "eventsUnsubscribeResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.EventsUnsubscribeResponse")
    public ApiEventsUnsubscribeResult eventsUnsubscribe(
        @WebParam(name = "session", targetNamespace = "")
        ApiSession session,
        @WebParam(name = "subscriptionId", targetNamespace = "")
        String subscriptionId);

    /**
     * 
     * @param id
     * @param session
     * @param entityName
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetEntityNotesResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEntityNotes", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetEntityNotes")
    @ResponseWrapper(localName = "getEntityNotesResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetEntityNotesResponse")
    public ApiGetEntityNotesResult getEntityNotes(
        @WebParam(name = "session", targetNamespace = "")
        ApiSession session,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "id", targetNamespace = "")
        Object id);

    /**
     * 
     * @param id
     * @param notesWhere
     * @param session
     * @param entityName
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetEntityNotesResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEntityNotesWhere", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetEntityNotesWhere")
    @ResponseWrapper(localName = "getEntityNotesWhereResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetEntityNotesWhereResponse")
    public ApiGetEntityNotesResult getEntityNotesWhere(
        @WebParam(name = "session", targetNamespace = "")
        ApiSession session,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "id", targetNamespace = "")
        Object id,
        @WebParam(name = "notesWhere", targetNamespace = "")
        String notesWhere);

    /**
     * 
     * @param id
     * @param session
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetNoteReferencesResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNoteReferences", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetNoteReferences")
    @ResponseWrapper(localName = "getNoteReferencesResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetNoteReferencesResponse")
    public ApiGetNoteReferencesResult getNoteReferences(
        @WebParam(name = "session", targetNamespace = "")
        ApiSession session,
        @WebParam(name = "id", targetNamespace = "")
        Object id);

    /**
     * 
     * @param session
     * @param entityId
     * @param noteId
     * @param entityName
     * @return
     *     returns com.bullhorn.apiservice.result.ApiAddNoteReferenceResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addNoteReference", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.AddNoteReference")
    @ResponseWrapper(localName = "addNoteReferenceResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.AddNoteReferenceResponse")
    public ApiAddNoteReferenceResult addNoteReference(
        @WebParam(name = "session", targetNamespace = "")
        ApiSession session,
        @WebParam(name = "noteId", targetNamespace = "")
        Object noteId,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "entityId", targetNamespace = "")
        Object entityId);

    /**
     * 
     * @param session
     * @param entityId
     * @param noteId
     * @param entityName
     * @return
     *     returns com.bullhorn.apiservice.result.ApiRemoveNoteReferenceResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeNoteReference", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.RemoveNoteReference")
    @ResponseWrapper(localName = "removeNoteReferenceResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.RemoveNoteReferenceResponse")
    public ApiRemoveNoteReferenceResult removeNoteReference(
        @WebParam(name = "session", targetNamespace = "")
        ApiSession session,
        @WebParam(name = "noteId", targetNamespace = "")
        Object noteId,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "entityId", targetNamespace = "")
        Object entityId);

    /**
     * 
     * @param session
     * @param privateLabelId
     * @param entityName
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetEntityMetadataResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEntityMetadata", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetEntityMetadata")
    @ResponseWrapper(localName = "getEntityMetadataResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetEntityMetadataResponse")
    public ApiGetEntityMetadataResult getEntityMetadata(
        @WebParam(name = "session", targetNamespace = "")
        ApiSession session,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "privateLabelId", targetNamespace = "")
        Object privateLabelId);

    /**
     * 
     * @param session
     * @param privateLabelId
     * @param typeId
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetEntityMetadataResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getJobOrderMetadata", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetJobOrderMetadata")
    @ResponseWrapper(localName = "getJobOrderMetadataResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetJobOrderMetadataResponse")
    public ApiGetEntityMetadataResult getJobOrderMetadata(
        @WebParam(name = "session", targetNamespace = "")
        ApiSession session,
        @WebParam(name = "typeId", targetNamespace = "")
        Object typeId,
        @WebParam(name = "privateLabelId", targetNamespace = "")
        Object privateLabelId);

    /**
     * 
     * @param count
     * @param session
     * @param subscriptionId
     * @param entityName
     */
    @WebMethod(operationName = "_eventsGenerateBogusEvents")
    @RequestWrapper(localName = "_eventsGenerateBogusEvents", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.EventsGenerateBogusEvents")
    @ResponseWrapper(localName = "_eventsGenerateBogusEventsResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.EventsGenerateBogusEventsResponse")
    public void eventsGenerateBogusEvents(
        @WebParam(name = "session", targetNamespace = "")
        ApiSession session,
        @WebParam(name = "subscriptionId", targetNamespace = "")
        String subscriptionId,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "count", targetNamespace = "")
        int count);

    /**
     * 
     * @param count
     * @param session
     * @param subscriptionId
     */
    @WebMethod(operationName = "_eventsGenerateBogusJobMatchSearchEvents")
    @RequestWrapper(localName = "_eventsGenerateBogusJobMatchSearchEvents", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.EventsGenerateBogusJobMatchSearchEvents")
    @ResponseWrapper(localName = "_eventsGenerateBogusJobMatchSearchEventsResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.EventsGenerateBogusJobMatchSearchEventsResponse")
    public void eventsGenerateBogusJobMatchSearchEvents(
        @WebParam(name = "session", targetNamespace = "")
        ApiSession session,
        @WebParam(name = "subscriptionId", targetNamespace = "")
        String subscriptionId,
        @WebParam(name = "count", targetNamespace = "")
        int count);

    /**
     * 
     * @param count
     * @param session
     * @param subscriptionId
     */
    @WebMethod(operationName = "_eventsGenerateBogusFieldMapChangeEvents")
    @RequestWrapper(localName = "_eventsGenerateBogusFieldMapChangeEvents", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.EventsGenerateBogusFieldMapChangeEvents")
    @ResponseWrapper(localName = "_eventsGenerateBogusFieldMapChangeEventsResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.EventsGenerateBogusFieldMapChangeEventsResponse")
    public void eventsGenerateBogusFieldMapChangeEvents(
        @WebParam(name = "session", targetNamespace = "")
        ApiSession session,
        @WebParam(name = "subscriptionId", targetNamespace = "")
        String subscriptionId,
        @WebParam(name = "count", targetNamespace = "")
        int count);

    /**
     * 
     * @param maxEvents
     * @param session
     * @param subscriptionId
     * @return
     *     returns com.bullhorn.apiservice.result.ApiEventsGetEventsResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "eventsGetEvents", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.EventsGetEvents")
    @ResponseWrapper(localName = "eventsGetEventsResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.EventsGetEventsResponse")
    public ApiEventsGetEventsResult eventsGetEvents(
        @WebParam(name = "session", targetNamespace = "")
        ApiSession session,
        @WebParam(name = "subscriptionId", targetNamespace = "")
        String subscriptionId,
        @WebParam(name = "maxEvents", targetNamespace = "")
        int maxEvents);

    /**
     * 
     * @param session
     * @param subscriptionId
     * @return
     *     returns com.bullhorn.apiservice.result.ApiEventsGetLastRequestIdResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "eventsGetLastRequestId", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.EventsGetLastRequestId")
    @ResponseWrapper(localName = "eventsGetLastRequestIdResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.EventsGetLastRequestIdResponse")
    public ApiEventsGetLastRequestIdResult eventsGetLastRequestId(
        @WebParam(name = "session", targetNamespace = "")
        ApiSession session,
        @WebParam(name = "subscriptionId", targetNamespace = "")
        String subscriptionId);

    /**
     * 
     * @param requestId
     * @param session
     * @param subscriptionId
     * @return
     *     returns com.bullhorn.apiservice.result.ApiEventsGetEventsResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "eventsRegetEvents", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.EventsRegetEvents")
    @ResponseWrapper(localName = "eventsRegetEventsResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.EventsRegetEventsResponse")
    public ApiEventsGetEventsResult eventsRegetEvents(
        @WebParam(name = "session", targetNamespace = "")
        ApiSession session,
        @WebParam(name = "subscriptionId", targetNamespace = "")
        String subscriptionId,
        @WebParam(name = "requestId", targetNamespace = "")
        long requestId);

    /**
     * 
     * @param arg0
     */
    @WebMethod(operationName = "_exportApiEnums")
    @RequestWrapper(localName = "_exportApiEnums", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.ExportApiEnums")
    @ResponseWrapper(localName = "_exportApiEnumsResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.ExportApiEnumsResponse")
    public void exportApiEnums(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param username
     * @param source
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getApplicationServerHost", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetApplicationServerHost")
    @ResponseWrapper(localName = "getApplicationServerHostResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetApplicationServerHostResponse")
    public String getApplicationServerHost(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "source", targetNamespace = "")
        String source);

}
