
package com.bullhorn.apiservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-hudson-208-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "EmailServiceException", targetNamespace = "http://apiservice.bullhorn.com/")
public class EmailServiceException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private EmailServiceException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public EmailServiceException_Exception(String message, EmailServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public EmailServiceException_Exception(String message, EmailServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.bullhorn.apiservice.EmailServiceException
     */
    public EmailServiceException getFaultInfo() {
        return faultInfo;
    }

}
