
package com.bullhorn.apiservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.bullhorn.apiservice.result.ApiResult;
import com.bullhorn.apiservice.result.FindEmailResult;
import com.bullhorn.apiservice.result.LoadEmailAttachmentResult;
import com.bullhorn.apiservice.result.SearchEmailResult;
import com.bullhorn.apiservice.session.ApiSession;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-hudson-208-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "EmailService", targetNamespace = "http://apiservice.bullhorn.com/")
@XmlSeeAlso({
    com.bullhorn.apiservice.result.ObjectFactory.class,
    com.bullhorn.apiservice.ObjectFactory.class,
    com.bullhorn.apiservice.session.ObjectFactory.class
})
public interface EmailService {


    /**
     * 
     * @param session
     * @param request
     * @return
     *     returns com.bullhorn.apiservice.result.SearchEmailResult
     * @throws EmailServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchEmail", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.SearchEmail")
    @ResponseWrapper(localName = "searchEmailResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.SearchEmailResponse")
    public SearchEmailResult searchEmail(
        @WebParam(name = "session", targetNamespace = "")
        ApiSession session,
        @WebParam(name = "request", targetNamespace = "")
        EmailSearchRequest request)
        throws EmailServiceException_Exception
    ;

    /**
     * 
     * @param session
     * @param request
     * @return
     *     returns com.bullhorn.apiservice.result.FindEmailResult
     * @throws EmailServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findEmail", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.FindEmail")
    @ResponseWrapper(localName = "findEmailResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.FindEmailResponse")
    public FindEmailResult findEmail(
        @WebParam(name = "session", targetNamespace = "")
        ApiSession session,
        @WebParam(name = "request", targetNamespace = "")
        FindEmailRequest request)
        throws EmailServiceException_Exception
    ;

    /**
     * 
     * @param session
     * @param request
     * @return
     *     returns com.bullhorn.apiservice.result.ApiResult
     * @throws EmailServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "moveEmail", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.MoveEmail")
    @ResponseWrapper(localName = "moveEmailResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.MoveEmailResponse")
    public ApiResult moveEmail(
        @WebParam(name = "session", targetNamespace = "")
        ApiSession session,
        @WebParam(name = "request", targetNamespace = "")
        MoveEmailRequest request)
        throws EmailServiceException_Exception
    ;

    /**
     * 
     * @param session
     * @param request
     * @return
     *     returns com.bullhorn.apiservice.result.ApiResult
     * @throws EmailServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteEmail", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.DeleteEmail")
    @ResponseWrapper(localName = "deleteEmailResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.DeleteEmailResponse")
    public ApiResult deleteEmail(
        @WebParam(name = "session", targetNamespace = "")
        ApiSession session,
        @WebParam(name = "request", targetNamespace = "")
        EmailModificationRequest request)
        throws EmailServiceException_Exception
    ;

    /**
     * 
     * @param session
     * @param request
     * @return
     *     returns com.bullhorn.apiservice.result.ApiResult
     * @throws EmailServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "purgeEmail", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.PurgeEmail")
    @ResponseWrapper(localName = "purgeEmailResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.PurgeEmailResponse")
    public ApiResult purgeEmail(
        @WebParam(name = "session", targetNamespace = "")
        ApiSession session,
        @WebParam(name = "request", targetNamespace = "")
        PurgeEmailRequest request)
        throws EmailServiceException_Exception
    ;

    /**
     * 
     * @param session
     * @param request
     * @return
     *     returns com.bullhorn.apiservice.result.ApiResult
     * @throws EmailServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createEmail", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.CreateEmail")
    @ResponseWrapper(localName = "createEmailResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.CreateEmailResponse")
    public ApiResult createEmail(
        @WebParam(name = "session", targetNamespace = "")
        ApiSession session,
        @WebParam(name = "request", targetNamespace = "")
        CreateEmailRequest request)
        throws EmailServiceException_Exception
    ;

    /**
     * 
     * @param session
     * @param request
     * @return
     *     returns com.bullhorn.apiservice.result.ApiResult
     * @throws EmailServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendEmail", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.SendEmail")
    @ResponseWrapper(localName = "sendEmailResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.SendEmailResponse")
    public ApiResult sendEmail(
        @WebParam(name = "session", targetNamespace = "")
        ApiSession session,
        @WebParam(name = "request", targetNamespace = "")
        CreateEmailRequest request)
        throws EmailServiceException_Exception
    ;

    /**
     * 
     * @param session
     * @param request
     * @return
     *     returns com.bullhorn.apiservice.result.LoadEmailAttachmentResult
     * @throws EmailServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "loadEmailAttachment", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.LoadEmailAttachment")
    @ResponseWrapper(localName = "loadEmailAttachmentResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.LoadEmailAttachmentResponse")
    public LoadEmailAttachmentResult loadEmailAttachment(
        @WebParam(name = "session", targetNamespace = "")
        ApiSession session,
        @WebParam(name = "request", targetNamespace = "")
        LoadEmailAttachmetRequest request)
        throws EmailServiceException_Exception
    ;

}
